name: Security Audit

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo-audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
